### PR TITLE
"ramaze console" was not working with 1.9.2

### PR DESCRIPTION
**Pull request by diegoviola**
I made this change and it seems to be workng now.

Thanks bougyman for helping me fix it.

### CODE REVIEW

**Comment by leejarvis** [comment]
This has already been fixed. Please use the [Ramaze/ramaze](http://github.com/Ramaze/ramaze) repository and update your remotes.

**Comment by diegoviola** [comment]
Thanks, what do you mean with "update your remotes"?

I already did gem update --system; gem update, etc

Is there a new ramaze version that has this fix?

**Comment by godfat** [comment]
If you had updated your forked repository with http://github.com/Ramaze/ramaze then you'll have noticed that it's already fixed. As far as I know, there's no gem release for this fix.

**Comment by diegoviola** [comment]
I didn't knew about the ramaze/ramaze repo. I thought the manveru/ramaze was the original one.

Thanks for letting me know and sorry about that. I'm still very new at Ramaze :)

**Comment by godfat** [comment]
Thanks for the patch. :)
Vote for gem release for this fix, and a pointer in this repository to point to the new repository. (or update them both)

**Pull request closed without merging**
